name: appwrite_function
description: Dart starter for Appwrite function.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:  
  dart_appwrite: ^7.2.0
  http: ^0.13.4
  sendgrid_mailer: ^0.1.3
      
dev_dependencies:
  lints: ^2.0.1
